backend:
  name: file-system

media_folder: site-data/images

collections:
  - name: "speakers" # Used in routes, e.g., /admin/collections/blog
    label: "Speakers" # Used in the UI
    folder: "site-data/speakers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}} {{company}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Speaker name", name: "name", widget: "string"}
      - {label: "Speaker title", name: "title", widget: "string"}
      - {label: "Speaker company", name: "company", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "custompathimage", customMediaPath: "./../images/"}

  - name: "conference-schedule" # Used in routes, e.g., /admin/collections/blog
    label: "Conference schedule" # Used in the UI
    folder: "site-data/schedule" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{speaker}}-{{talkName}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Conference day name", name: "conferenceDay", widget: "string"}
      - {label: "Talk start date", name: "start", widget: "string"}
      - {label: "Talk end date", name: "end", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Talk name", name: "talkName", widget: "string"}
  - name: "sponsors-list" # Used in routes, e.g., /admin/collections/blog
    label: "Sponsors list" # Used in the UI
    folder: "site-data/sponsors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Order", name: "position", widget: "string"}
      - {
          label: "Sponsor group(gold, platinum, media...)",
          name: "group",
          widget: "select",
          required: false,
          options: ['', 'Sponsors', 'Platinum', 'Gold', 'Silver', 'Media']
        }
      - {label: "Sponsor name", name: "name", widget: "string"}
      - {label: "Sponsor logo", name: "logo", widget: "custompathimage", customMediaPath: "./../images/"}
      - {label: "Link url", name: "url", widget: "string"}
  - name: "footer-links" # Used in routes, e.g., /admin/collections/blog
    label: "Footer links" # Used in the UI
    folder: "site-data/footer/links" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{label}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Order", name: "position", widget: "string"}
      - {label: "Link label", name: "label", widget: "string"}
      - {label: "Link url", name: "url", widget: "string"}
      - {label: "logo", name: "logo", widget: "custompathimage", customMediaPath: "./../../images/", required: false}
      - {label: "Icon class (font awsome)", name: "iconClass", widget: "string", required: false}