backend:
  name: github
  repo: 5-11/gatsby-netlify

publish_mode: editorial_workflow

media_folder: site-data/images
public_folder: /uploads


collections:
  - name: "speakers" # Used in routes, e.g., /admin/collections/blog
    label: "Speakers" # Used in the UI
    folder: "site-data/speakers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{speaker}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Speaker name", name: "name", widget: "string"}
      - {label: "Speaker title", name: "title", widget: "string"}
      - {label: "Speaker company", name: "company", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "string"}